# Generated by Django 5.2.17 on 2026-10-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('URGENT_REORDER', 'Urgent Reorder'), ('OVERSTOCK', 'Overstock'), ('OPTIMAL', 'Optimal')], max_length=50)),
                ('explanation', models.TextField()),
                ('recommended_order_quantity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
