# Generated by Django 6.1.1 on 2026-10-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_id_alter_store_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='subscription_plan',
            field=models.CharField(choices=[('STARTER', 'Starter'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], default='STARTER', max_length=20),
        ),
    ]
